FROM python:3.11-slim

ARG HUGGINGFACEHUB
ARG PINECONE

ENV HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB}
ENV PINECONE_API_KEY=${PINECONE}

WORKDIR /RAG_ChatPDF

COPY . /RAG_ChatPDF

RUN pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit","run","main.py"]